### ISSUE TITLE
konwledge检索

### ISSUE THREAD

**Issue by hit-syh** [Mingxiao-Li/DMMGR#1]
你好我在复现您这个模型，现在如果用fact和您达到了一样的精度但是在所有的fact-triples中用余弦相似度根本检索不到真的fact，能请教下您当初怎么做的吗？

**Comment by Mingxiao-Li** [comment]
> 1190201101

你好 retrieval不是我们的重点所以 没有详细说， 算余弦相似度的前需要做一个名词的检测和filter， 用knowledge base里的名词来做， 然后需要根据这个文章 https://proceedings.neurips.cc/paper/2018/file/c26820b8a4c1b3c2aa868d6d57e14a79-Paper.pdf 的关系判断网络 进一步缩减空间

**Comment by hit-syh** [comment]
十分感谢，我再尝试下！

**Comment by Mingxiao-Li** [comment]
> 十分感谢，我再尝试下！

嗯嗯 好的，这个代码之前放在我们服务器上，后面服务器文件系统换了 不知道被放到哪里了，最近比较忙， 等空了我找一下 整理整理
